### ISSUE TITLE
App starts with blank screen

### ISSUE THREAD

**Issue by Delicious-Bacon** [tobagin/whakarere#4]
Straight to the logs:

```
$ flatpak run com.mudeprolinux.whakarere
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x551: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x551: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x551: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

This is what I've seen on Wails: https://github.com/wailsapp/wails/issues/2977

Any ideas?

**Comment by db47h** [comment]
You can try this:

    $ flatpak run --env=WEBKIT_DISABLE_DMABUF_RENDERER=1 com.mudeprolinux.whakarere

**Comment by tobagin** [comment]
Since we no longer using webkit webview in the current internal build, this shouldn't be an issue going forward.

**Comment by Delicious-Bacon** [comment]
> Since we no longer using webkit webview in the current internal build, this shouldn't be an issue going forward.

@tobagin so a new update will solve it?

Using the env variable @db47h mentioned makes the app run.

**Comment by tobagin** [comment]
yes when the new release comes out, you wont have this problem anymore, since we'll no longer be using webkit in the app and that problem is specific to the webkit component.
